from __future__ import annotations

from llm4unroll.dsl.schema import ActionSpec, FeatureSpec, PolicySpec, SafetySpec, StateSpec


ALGORITHM_REGISTRY = {
    "FISTA": PolicySpec(
        algorithm="FISTA",
        description="Unrolled FISTA policy for LASSO-like objectives.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "grad_norm",
                "step_norm",
                "tau",
                "momentum",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "obj", "obj_prev", "tau", "momentum"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "obj": FeatureSpec("obj", kind="number"),
                "obj_prev": FeatureSpec("obj_prev", kind="number"),
                "gap": FeatureSpec("gap", kind="number"),
                "tau": FeatureSpec("tau", kind="number"),
                "momentum": FeatureSpec("momentum", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_tau", 1e-6, 1e2, arity=1, category="tau", conflicts_with=["scale_tau"]),
            ActionSpec("scale_tau", 0.2, 5.0, arity=1, category="tau", conflicts_with=["set_tau"]),
            ActionSpec("set_momentum", 0.0, 0.999, arity=1, category="momentum"),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, min_tau=1e-6, max_tau=1e2),
    ),
    "PDHG": PolicySpec(
        algorithm="PDHG",
        description="Primal-dual hybrid gradient policy for synthetic LP relaxations.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "r_p_norm",
                "r_d_norm",
                "violation",
                "tau",
                "sigma",
                "theta",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "r_p_norm", "r_d_norm", "tau", "sigma"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "r_p_norm": FeatureSpec("r_p_norm", kind="number"),
                "r_d_norm": FeatureSpec("r_d_norm", kind="number"),
                "violation": FeatureSpec("violation", kind="number"),
                "tau": FeatureSpec("tau", kind="number"),
                "sigma": FeatureSpec("sigma", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_tau", 1e-6, 1e2, arity=1, category="tau", conflicts_with=["scale_tau"]),
            ActionSpec("set_sigma", 1e-6, 1e2, arity=1, category="sigma", conflicts_with=["scale_sigma"]),
            ActionSpec("scale_tau", 0.2, 5.0, arity=1, category="tau", conflicts_with=["set_tau"]),
            ActionSpec("scale_sigma", 0.2, 5.0, arity=1, category="sigma", conflicts_with=["set_sigma"]),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(
            require_fallback=True,
            residual_explosion_factor=1e3,
            min_tau=1e-6,
            max_tau=1e2,
            min_sigma=1e-6,
            max_sigma=1e2,
        ),
    ),
    "ADMM": PolicySpec(
        algorithm="ADMM",
        description="ADMM policy for diagonal QP with box constraints.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "r_p_norm",
                "r_d_norm",
                "violation",
                "rho",
                "alpha",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "r_p_norm", "r_d_norm", "rho"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "r_p_norm": FeatureSpec("r_p_norm", kind="number"),
                "r_d_norm": FeatureSpec("r_d_norm", kind="number"),
                "rho": FeatureSpec("rho", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_rho", 1e-6, 1e3, arity=1, category="rho", conflicts_with=["scale_rho"]),
            ActionSpec("scale_rho", 0.2, 5.0, arity=1, category="rho", conflicts_with=["set_rho"]),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, min_rho=1e-6, max_rho=1e3),
    ),
    "DRS": PolicySpec(
        algorithm="DRS",
        description="Douglas-Rachford policy for feasibility-style projections with relaxation control.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "residual_norm",
                "dual_residual",
                "lambda_relax",
                "step_clip",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "residual_norm"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "obj": FeatureSpec("obj", kind="number"),
                "obj_prev": FeatureSpec("obj_prev", kind="number"),
                "gap": FeatureSpec("gap", kind="number"),
                "residual_norm": FeatureSpec("residual_norm", kind="number"),
                "dual_residual": FeatureSpec("dual_residual", kind="number"),
                "lambda_relax": FeatureSpec("lambda_relax", kind="number"),
                "step_clip": FeatureSpec("step_clip", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_lambda_relax", 0.05, 1.95, arity=1, category="relaxation", conflicts_with=["scale_lambda_relax"]),
            ActionSpec("scale_lambda_relax", 0.5, 1.5, arity=1, category="relaxation", conflicts_with=["set_lambda_relax"]),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-3, 5.0, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, residual_explosion_factor=1e3),
    ),
    "ALM": PolicySpec(
        algorithm="ALM",
        description="Augmented Lagrangian policy with penalty scheduling and clipped primal updates.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "violation",
                "rho",
                "dual_residual",
                "grad_norm",
                "clip_scale",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "violation", "rho"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "obj": FeatureSpec("obj", kind="number"),
                "obj_prev": FeatureSpec("obj_prev", kind="number"),
                "gap": FeatureSpec("gap", kind="number"),
                "violation": FeatureSpec("violation", kind="number"),
                "rho": FeatureSpec("rho", kind="number"),
                "dual_residual": FeatureSpec("dual_residual", kind="number"),
                "grad_norm": FeatureSpec("grad_norm", kind="number"),
                "clip_scale": FeatureSpec("clip_scale", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_rho", 1e-6, 1e3, arity=1, category="rho", conflicts_with=["scale_rho"]),
            ActionSpec("scale_rho", 0.2, 5.0, arity=1, category="rho", conflicts_with=["set_rho"]),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-3, 5.0, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, min_rho=1e-6, max_rho=1e3),
    ),
    "PCG": PolicySpec(
        algorithm="PCG",
        description="Preconditioned conjugate-gradient policy for inner linear-system control.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "residual_norm",
                "residual_ratio",
                "direction_curvature",
                "precond_quality",
                "step_clip",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "residual_norm"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "obj": FeatureSpec("obj", kind="number"),
                "obj_prev": FeatureSpec("obj_prev", kind="number"),
                "gap": FeatureSpec("gap", kind="number"),
                "residual_norm": FeatureSpec("residual_norm", kind="number"),
                "residual_ratio": FeatureSpec("residual_ratio", kind="number"),
                "direction_curvature": FeatureSpec("direction_curvature", kind="number"),
                "precond_quality": FeatureSpec("precond_quality", kind="number"),
                "step_clip": FeatureSpec("step_clip", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-3, 5.0, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, residual_explosion_factor=1e3),
    ),
    "LNS_REPAIR": PolicySpec(
        algorithm="LNS_REPAIR",
        description="Relaxation-guided repair policy with neighbourhood-size control and clipped repair steps.",
        state=StateSpec(
            allowed_features=[
                "k",
                "incumbent_obj",
                "best_bound",
                "mip_gap",
                "lp_gap",
                "fractionality",
                "violation",
                "neighbourhood_size",
                "repair_progress",
                "step_clip",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "mip_gap", "fractionality", "neighbourhood_size"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "incumbent_obj": FeatureSpec("incumbent_obj", kind="number"),
                "best_bound": FeatureSpec("best_bound", kind="number"),
                "mip_gap": FeatureSpec("mip_gap", kind="number"),
                "lp_gap": FeatureSpec("lp_gap", kind="number"),
                "fractionality": FeatureSpec("fractionality", kind="number"),
                "violation": FeatureSpec("violation", kind="number"),
                "neighbourhood_size": FeatureSpec("neighbourhood_size", kind="number"),
                "repair_progress": FeatureSpec("repair_progress", kind="number"),
                "step_clip": FeatureSpec("step_clip", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_neighbourhood_size", 0.05, 0.95, arity=1, category="neighbourhood", conflicts_with=["scale_neighbourhood_size"]),
            ActionSpec("scale_neighbourhood_size", 0.5, 1.5, arity=1, category="neighbourhood", conflicts_with=["set_neighbourhood_size"]),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 0.1, 2.0, arity=1, category="stability"),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, residual_explosion_factor=1e3),
    ),
}
