from __future__ import annotations

from llm4unroll.dsl.schema import ActionSpec, FeatureSpec, PolicySpec, SafetySpec, StateSpec


ALGORITHM_REGISTRY = {
    "FISTA": PolicySpec(
        algorithm="FISTA",
        description="Unrolled FISTA policy for LASSO-like objectives.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "grad_norm",
                "step_norm",
                "tau",
                "momentum",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "obj", "obj_prev", "tau", "momentum"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "obj": FeatureSpec("obj", kind="number"),
                "obj_prev": FeatureSpec("obj_prev", kind="number"),
                "gap": FeatureSpec("gap", kind="number"),
                "tau": FeatureSpec("tau", kind="number"),
                "momentum": FeatureSpec("momentum", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_tau", 1e-6, 1e2, arity=1, category="tau", conflicts_with=["scale_tau"]),
            ActionSpec("scale_tau", 0.2, 5.0, arity=1, category="tau", conflicts_with=["set_tau"]),
            ActionSpec("set_momentum", 0.0, 0.999, arity=1, category="momentum"),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, min_tau=1e-6, max_tau=1e2),
    ),
    "PDHG": PolicySpec(
        algorithm="PDHG",
        description="Primal-dual hybrid gradient policy for synthetic LP relaxations.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "r_p_norm",
                "r_d_norm",
                "violation",
                "tau",
                "sigma",
                "theta",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "r_p_norm", "r_d_norm", "tau", "sigma"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "r_p_norm": FeatureSpec("r_p_norm", kind="number"),
                "r_d_norm": FeatureSpec("r_d_norm", kind="number"),
                "violation": FeatureSpec("violation", kind="number"),
                "tau": FeatureSpec("tau", kind="number"),
                "sigma": FeatureSpec("sigma", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_tau", 1e-6, 1e2, arity=1, category="tau", conflicts_with=["scale_tau"]),
            ActionSpec("set_sigma", 1e-6, 1e2, arity=1, category="sigma", conflicts_with=["scale_sigma"]),
            ActionSpec("scale_tau", 0.2, 5.0, arity=1, category="tau", conflicts_with=["set_tau"]),
            ActionSpec("scale_sigma", 0.2, 5.0, arity=1, category="sigma", conflicts_with=["set_sigma"]),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(
            require_fallback=True,
            residual_explosion_factor=1e3,
            min_tau=1e-6,
            max_tau=1e2,
            min_sigma=1e-6,
            max_sigma=1e2,
        ),
    ),
    "ADMM": PolicySpec(
        algorithm="ADMM",
        description="ADMM policy for diagonal QP with box constraints.",
        state=StateSpec(
            allowed_features=[
                "k",
                "obj",
                "obj_prev",
                "gap",
                "r_p_norm",
                "r_d_norm",
                "violation",
                "rho",
                "alpha",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "r_p_norm", "r_d_norm", "rho"],
            feature_types={
                "k": FeatureSpec("k", kind="number"),
                "r_p_norm": FeatureSpec("r_p_norm", kind="number"),
                "r_d_norm": FeatureSpec("r_d_norm", kind="number"),
                "rho": FeatureSpec("rho", kind="number"),
                "instance_features": FeatureSpec("instance_features", kind="dict", default_kind="dict"),
            },
        ),
        actions=[
            ActionSpec("set_rho", 1e-6, 1e3, arity=1, category="rho", conflicts_with=["scale_rho"]),
            ActionSpec("scale_rho", 0.2, 5.0, arity=1, category="rho", conflicts_with=["set_rho"]),
            ActionSpec("damp", 0.05, 1.0, arity=1, category="stability"),
            ActionSpec("restart", arity=0, category="restart"),
            ActionSpec("clip_update", 1e-6, 1e2, arity=1, category="stability"),
            ActionSpec("fallback", arity=0, category="safety"),
        ],
        safety=SafetySpec(require_fallback=True, min_rho=1e-6, max_rho=1e3),
    ),
    "DRS": PolicySpec(
        algorithm="DRS",
        description="Douglas-Rachford placeholder spec for future phases.",
        state=StateSpec(
            allowed_features=["k", "obj", "obj_prev", "gap", "residual_norm", "stagnation_count", "instance_features"],
            required_features=["k", "residual_norm"],
        ),
        actions=[ActionSpec("restart", arity=0), ActionSpec("damp", 0.05, 1.0, arity=1), ActionSpec("fallback", arity=0)],
    ),
    "ALM": PolicySpec(
        algorithm="ALM",
        description="Augmented Lagrangian placeholder spec for future phases.",
        state=StateSpec(
            allowed_features=["k", "obj", "obj_prev", "gap", "violation", "rho", "stagnation_count", "instance_features"],
            required_features=["k", "violation", "rho"],
        ),
        actions=[
            ActionSpec("set_rho", 1e-6, 1e3, arity=1),
            ActionSpec("scale_rho", 0.2, 5.0, arity=1),
            ActionSpec("restart", arity=0),
            ActionSpec("damp", 0.05, 1.0, arity=1),
            ActionSpec("fallback", arity=0),
        ],
        safety=SafetySpec(require_fallback=True, min_rho=1e-6, max_rho=1e3),
    ),
    "PCG": PolicySpec(
        algorithm="PCG",
        description="Phase 1 placeholder for inner-solver policy control.",
        state=StateSpec(
            allowed_features=["k", "residual_norm", "residual_ratio", "direction_curvature", "stagnation_count", "instance_features"],
            required_features=["k", "residual_norm"],
        ),
        actions=[ActionSpec("restart", arity=0), ActionSpec("damp", 0.05, 1.0, arity=1), ActionSpec("fallback", arity=0)],
    ),
    "LNS_REPAIR": PolicySpec(
        algorithm="LNS_REPAIR",
        description="Phase 1 placeholder for relaxation-repair policies.",
        state=StateSpec(
            allowed_features=[
                "k",
                "incumbent_obj",
                "best_bound",
                "mip_gap",
                "lp_gap",
                "fractionality",
                "violation",
                "neighbourhood_size",
                "stagnation_count",
                "instance_features",
            ],
            required_features=["k", "mip_gap", "fractionality", "neighbourhood_size"],
        ),
        actions=[ActionSpec("damp", 0.05, 1.0, arity=1), ActionSpec("restart", arity=0), ActionSpec("fallback", arity=0)],
    ),
}
